### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by avivajpeyi** [dunnkers/nbconvert-blog-template#1]
Hey! could you host an example somewhere?

**Comment by dunnkers** [comment]
Hi @avivajpeyi ! An example for how to use the template, or as to how it looks?

I've got a couple webpages online that show the template:

- https://dunnkers.com/music-key-classification/
- https://dunnkers.com/god-components/

Either way, good idea. Will add that to the repo!

**Comment by dunnkers** [comment]
I added some screenshots ✓ Hope that solves it
